config/routes.rb
Feedback::Engine.routes.draw do
  resources :forms do
    get 'questions'
    get 'batches'
    match 'submission', via: [:get, :patch]

    get 'reports/by_teacher'
    get 'reports/by_form'
  end
end

app/models/feedback/answer.rb
module Feedback
  class Answer < ActiveRecord::Base
    belongs_to :form
    belongs_to :question
    belongs_to :student
    belongs_to :batch
    belongs_to :teacher, class_name: "Employee"
    belongs_to :subject
  end
end

app/models/feedback/form.rb
module Feedback
  class Form < ActiveRecord::Base
    belongs_to :creator, class_name: "User"
    has_many   :sections
    has_many   :questions, through: :sections
    has_and_belongs_to_many :batches, class_name: "Batch"

    validates :name, presence: true
    validates :name, uniqueness: { scope: :creator }
    validates :start_date, presence: true
    validates :end_date, presence: true

    accepts_nested_attributes_for :sections
  end
end

app/models/feedback/question.rb
module Feedback
  class Question < ActiveRecord::Base
    belongs_to :section
    has_many   :answers

    def to_s
      content
    end
  end
end

app/models/feedback/remark.rb
module Feedback
  class Remark < ActiveRecord::Base
    belongs_to :form
    belongs_to :student
    belongs_to :teacher, class_name: "Employee"
  end
end

app/models/feedback/section.rb
module Feedback
  class Section < ActiveRecord::Base
    belongs_to :form
    has_many   :questions
    
    accepts_nested_attributes_for :questions
  end
end

app/controllers/feedback/application_controller.rb
class Feedback::ApplicationController < ApplicationController
  layout 'layouts/application'
end

app/controllers/feedback/forms_controller.rb
require_dependency "feedback/application_controller"

module Feedback
  class FormsController < ApplicationController
    before_action :set_form, only: [:show, :edit, :update, :destroy]

    # GET /forms
    def index
      @forms = policy_scope(Form.all)
      authorize @forms
    end

    # GET /forms/1
    def show
    end

    # GET /forms/new
    def new
      @form = Form.new
      authorize(@form)
    end

    # GET /forms/1/edit
    def edit
    end

    # POST /forms
    def create
      @form = Form.new(form_params)
      authorize(@form)
      
      if @form.save
        redirect_to forms_url, notice: 'Form was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /forms/1
    def update
      if @form.update(form_params)
        redirect_to @form, notice: 'Form was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /forms/1
    def destroy
      @form.destroy
      redirect_to forms_url, notice: 'Form was successfully destroyed.'
    end

    def questions
      @form = Form.find(params[:form_id])
      authorize(@form)
    end

    def submission
      @form = Form.find(params[:form_id])
      authorize(@form)
      @student = Student.find_by(user: current_user)
      
      respond_to do |format|
        format.html do
          @teachers = []
          @subjects = @student.batch.subjects
          @subjects.each do |subject|
            subject.teachers.each do |teacher|
              answers = Answer.where(form: @form, student: @student, 
                teacher: teacher, subject: subject)
              @teachers << {id: teacher.id, subject_id: subject.id,
                name: teacher.to_s, subject: subject.to_s} if answers.empty?
            end
          end
        end

        format.js do
          @teacher = Employee.find(form_params[:teacher_id])
          @subject = Subject.find(form_params[:subject_id])
          form_params[:question_ids].each_with_index do |question, index|
            @question = Question.find(question)
            Answer.create!(form: @form, question: @question, student: @student,
              batch: @student.batch, teacher: @teacher, subject: @subject, 
              points: form_params[:question_points][index])
          end
          Remark.create!(form: @form, student: @student, 
            teacher: @teacher, content: form_params[:remark]) unless form_params[:remark].nil?
        end
      end
    end

    def batches
      @form = Form.find(params[:form_id])
      authorize(@form)
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_form
        @form = Form.find(params[:id])
        authorize(@form)
      end

      # Only allow a trusted parameter "white list" through.
      def form_params
        params.require(:form).permit(:creator_id, :name, :start_date, 
          :end_date, :teacher_id, :subject_id, :remark, batch_ids: [],
          sections_attributes: [:id, :title, questions_attributes: [:id, :content]],
          question_ids:[], question_points:[])
      end
  end
end

app/controllers/feedback/reports_controller.rb
require_dependency "feedback/application_controller"

module Feedback
  class ReportsController < ApplicationController
    def by_teacher
      authorize Form.find(params[:form_id])
      @teacher = current_user
      @subjects = Feedback::Answer.where(form_id: 1, teacher_id: 2)
      .group(:subject_id).select(:subject_id).map{ |answer| answer.subject}
    end

    def by_form
      @form = Form.find(params[:form_id])
      authorize @form

      @statistics = []
      @form.questions.each do |question|
        subjects = []
        Feedback::Answer.where(form_id: @form, question: question)
        .group(:teacher_id, :subject_id).average(:points).each do |subject, average|
        subjects << [
          [Employee.find(subject[0]).to_s,
          Subject.find(subject[1]).to_s],
          average
          ]
        end
        @statistics << {question: question.content, data: subjects}
      end
    end
  end
end

app/helpers/feedback/application_helper.rb
module Feedback
  module ApplicationHelper
    def method_missing(method, *args, &block)
      if (method.to_s.end_with?('_path') || method.to_s.end_with?('_url')) && main_app.respond_to?(method)
        main_app.send(method, *args)
      else
        super
      end
    end
  end
end

app/helpers/feedback/forms_helper.rb
module Feedback
  module FormsHelper
  end
end

app/helpers/feedback/report_helper.rb
module Feedback
  module ReportHelper
  end
end

app/views/feedback/forms/_form.html.haml
= form_for @form, html: {class: "ui compact fluid form"} do |f|
  - if @form.errors.any?
    %div.ui.negative.message
      %h2= "#{pluralize(@form.errors.count, "error")} prohibited this form from being saved:"
      %ul
        - @form.errors.full_messages.each do |message|
          %li= message

  = f.hidden_field :creator_id, value: current_user.id
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :start_date
    = f.text_field :start_date, class: "datepicker"
  .field
    = f.label :end_date
    = f.text_field :end_date, class: "datepicker"
  .actions
    = f.submit class: "ui submit button"

app/views/feedback/forms/_question_fields.html.haml
.ui.segment
  = f.text_field :content, placeholder: "Question"

app/views/feedback/forms/_section_accordion_fields.html.haml
.accordion
  .title
    %i.dropdown.icon
    = f.object.title

  .ui.stacked.secondary.segment.content
    = f.label :title
    = f.text_field :title

    = f.fields_for :questions do |question|
      = render "question_fields", f: question
    .add_question
      %br
      %i.square.plus.icon
      = link_to_add_fields "Question", f, :questions

app/views/feedback/forms/_section_fields.html.haml
.ui.stacked.secondary.segment
  = f.label :title
  = f.text_field :title

  = f.fields_for :questions do |question|
    = question.text_field :content, placeholder: "Question"

  .add_question
    %br
    %i.square.plus.icon
    = link_to_add_fields "Question", f, :questions

app/views/feedback/forms/_submission_form.html.haml
= form_for(@form, url:{ action: :submission}, remote: true, html: {class: "ui fluid form"}) do |f|
  = hidden_field_tag "form[teacher_id]", teacher, id: "teacher_" + teacher.to_s
  = hidden_field_tag "form[subject_id]", subject, id: "subject_" + subject.to_s
  %table.ui.celled.striped.table
    = f.fields_for :sections, include_id: false do |section|
      %thead
        %tr
          %th= ("A".ord + section.index).chr
          %th{colspan: "11"}= section.object.title
      %tbody
        = section.fields_for :questions do |question|
          %tr
            %td= question.index + 1
            %td= question.object.content
            %td
              = hidden_field_tag "form[question_points][]", 0, id: "points_" + question.object.id.to_s
              = hidden_field_tag "form[question_ids][]", question.object.id, id: "question_" + question.object.id.to_s
              .ui.star.feedback.rating{"data-max-rating"=>"10"}
        %tr
          %td{colspan: 3}
            = text_area_tag "form[remark]", nil, id: "remark_" + Time.new.to_i.to_s, rows: 2, placeholder: "Any other remarks"
  = f.submit 'Save', disabled: "true", class: "ui negative button"

app/views/feedback/forms/batches.html.haml
= form_for @form, html: {class: "ui compact fluid form"} do |f|
  - if @form.errors.any?
    %div.ui.negative.message
      %h2= "#{pluralize(@form.errors.count, "error")} prohibited this form from being saved:"
      %ul
        - @form.errors.full_messages.each do |message|
          %li= message
  .field
    = f.collection_select :batch_ids, Batch.active.all, :id, :full_name, {}, multiple: true
  .actions
    = f.submit class: "ui submit button"

app/views/feedback/forms/edit.html.haml
%h1 Editing Feedback Form

= render 'form'

app/views/feedback/forms/index.html.haml
%h1 Feedback Forms

%table.ui.table
  %thead
    %tr
      %th Name
      %th Start date
      %th End date
      %th{colspan: "6"}

  %tbody
    - @forms.each do |form|
      %tr
        %td
          = form.name
        %td
          = form.start_date
        %td
          = form.end_date

        - if policy(form).show?
          %td
            = link_to 'View Form', form

        - if policy(form).by_form?
          %td
            = link_to 'Overall Report', form_reports_by_form_path(form)

        - if policy(form).by_teacher?
          %td
            = link_to 'Individual Report', form_reports_by_teacher_path(form)

        - if policy(form).batches?
          %td
            = link_to 'Batches', form_batches_path(form)

        - if policy(form).questions?
          %td
            = link_to 'Questions', form_questions_path(form)

        - if policy(form).edit?
          %td
            = link_to 'Edit', edit_form_path(form)

        - if policy(form).destroy?
          %td
            = link_to 'Remove', form, method: :delete, data: { confirm: 'Are you sure?' }

        - if policy(form).submission?
          %td
            = link_to 'Submit Feedback', form_submission_path(form)
<br>

= link_to 'New Form', new_form_path

app/views/feedback/forms/new.html.haml
%h1 New Feedback Form

= render 'form'

app/views/feedback/forms/questions.html.haml
= form_for(@form, html: {class: "ui fluid form"}) do |f|
  - if @form.errors.any?
    .error_explanation
      %h2= "#{pluralize(@form.errors.count, "error")} prohibited this form from being saved:"
      %ul
        - @form.errors.full_messages.each do |message|
          %li= message

  .ui.accordion
    = f.fields_for :sections do |section|
      = render "section_accordion_fields", f: section

  .ui.divider
  .add_section
    %br
    %i.square.plus.icon
    = link_to_add_fields "Section", f, :sections
  .actions
    <br>
    = f.submit class: "ui submit button"

app/views/feedback/forms/show.html.haml
%table.ui.celled.table
  - @form.sections.each_with_index do |section, i|
    %thead
      %tr
        %th= ("A".ord + i).chr
        %th= section.title
    - section.questions.each_with_index do |question, j|
      %tbody
        %tr
          %td= 1+j
          %td
            = question.content

app/views/feedback/forms/submission.html.haml
%h1 Feedback

.ui.segment
  .ui.accordion
    - @teachers.each_with_index do |teacher, index|
      .accordion.field{"data-index" => index}
        .title
          %i.icon.dropdown
          = teacher[:name] + " - " + teacher[:subject]
        .content.field
          = render 'submission_form', teacher: teacher[:id], subject: teacher[:subject_id]

app/views/feedback/reports/by_form.html.haml
- @statistics.each do |graph|
  .ui.tertiary.segment
    %h5= graph[:question]
    = column_chart graph[:data]

    %table.ui.table
      %thead
        %tr
          %th Name
          %th Subject
          %th Points

      %tbody
        - graph[:data].each do |subject|
          %tr
            %td= subject[0][0]
            %td= subject[0][1]
            %td= subject[1]

app/views/feedback/reports/by_teacher.html.erb
<%=
  column_chart @subjects.map{ |subject|
  { name: subject.to_s, data: Feedback::Answer
    .where(form_id: 1, teacher_id: 2, subject: subject)
    .group(:question).average(:points) }
  }
%>

app/views/layouts/feedback/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Feedback</title>
  <%= stylesheet_link_tag    "feedback/application", media: "all" %>
  <%= javascript_include_tag "feedback/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>